### PR TITLE
WASI: Add stdio and file system support

### PR DESCRIPTION
**Pull request by Gaboose**
Hi! I extended the `wasi` package to support writing and reading from Stdin, Stdout and Stderr. By default the host proccess's Stdin, Stdout and Stderr is used, but custom `io.Reader`/`io.Writer`s can also be set, which is not possible when using wasmtime-go yet (without creating a temporary file https://github.com/bytecodealliance/wasmtime-go/issues/34).

Also added rudimentary support for preopened directories, so that wasm binaries can open, read and write to files.

The `wasi` package now supports a few more methods (relates to issue https://github.com/mathetake/gasm/issues/10):
- `fd_prestat_get`
- `fd_prestat_dir_name`
- `path_open`
- `fd_read`
- `fd_close`

I added a `wasi.WASI` type, which holds preopened directories, custom readers and writers and other options for a particular wasi environment.

Example usage:
```go
vm, err := wasm.NewVM(mod, wasi.New(
	wasi.Stdin(myReader),
	wasi.Stdout(myWriter),
	wasi.Stderr(myErrWriter),
	wasi.Preopen(".", wasi.DirFS(".")),
).Modules())
if err != nil {
	panic(err)
}

if err := vm.ExecExportedFunction("_start"); err != nil {
	panic(err)
}
```

I couldn't get go code compiled with tinygo to read from Stdin, write to Stderr, or open files. Unless I'm missing something, I think tinygo doesn't support that yet :\ (EDIT: but maybe not for long: https://github.com/tinygo-org/tinygo/pull/1659, https://github.com/tinygo-org/tinygo/issues/1505). But rust does, so I added `rust_stdio.rs` and `rust_file_system.rs` to `examples/wasm` and their respective wasm binaries to test wasi support in `gasm` (https://github.com/mathetake/gasm/issues/4).

Let me know if you want anything changed, before merging.

### CODE REVIEW

**Comment by mathetake** [comment]
@Gaboose Thanks you so much! This is really awesome. Let me review in the next weekend.

**Comment by mathetake** [comment]
@Gaboose sorry for being late, code LGTM thank you so much! 

TinyGo's file support has landed the dev branch (https://github.com/tinygo-org/tinygo/pull/1659) so it's available in the `tinygo/tinyo-dev:latest` image (https://hub.docker.com/r/tinygo/tinygo-dev). Could you try TinyGo, and hopefully remove rust codes? Thanks!

**Comment by Gaboose** [comment]
Nice work on the https://github.com/tinygo-org/tinygo/pull/1659! I rebuilt `stdio.go` and `file_system.go` examples with the new TinyGo, and the tests now pass, so I removed the rust code and the corresponding wasm modules.

The new TinyGo modules import one more method `fd_fdstat_get`, which I implemented just enough for the tests to pass.

**Review by mathetake — APPROVED** [review]
Super!

**Comment by mathetake** [comment]
@Gaboose Thank you so much for your work!

**Pull request merged**
